# Generated by Django 5.1.7 on 2025-03-29 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositoriogithub',
            name='git_token',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
