# Generated by Django 5.1.7 on 2025-03-29 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0002_repositoriogithub_git_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repositoriogithub',
            name='git_token',
        ),
    ]
