# Generated by Django 5.1.7 on 2025-04-05 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0005_atividadegithub_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repositoriogithub',
            name='git_token',
        ),
        migrations.RemoveField(
            model_name='repositoriogithub',
            name='github_username',
        ),
    ]
