# Generated by Django 5.1.7 on 2025-04-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0006_remove_repositoriogithub_git_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositoriogithub',
            name='github_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
