# Generated by Django 5.1.7 on 2025-04-04 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='trello_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
