# Generated by Django 5.1.7 on 2025-04-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_trello_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='github_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='github_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
