# Generated by Django 5.2 on 2025-04-15 19:01

import employees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0006_employee_github_token_employee_github_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="employee_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=employees.models.user_directory_path,
                verbose_name="Imagem de Perfil",
            ),
        ),
    ]
