# Generated by Django 5.2 on 2025-04-04 16:35

import validations.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_usermodel_cnpj"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="cnpj",
            field=models.CharField(
                db_index=True,
                max_length=18,
                unique=True,
                validators=[validations.validators.validate_cnpj],
                verbose_name="CNPJ",
            ),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="password",
            field=models.CharField(max_length=255, null=True, verbose_name="Senha"),
        ),
    ]
