# Generated by Django 5.2 on 2025-04-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_usermodel_cnpj_alter_usermodel_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profile_pictures/",
                verbose_name="Foto de perfil",
            ),
        ),
    ]
