# Generated by Django 5.2 on 2025-04-04 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_usermodel_profile_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usermodel",
            name="profile_picture",
        ),
    ]
