"""
Django settings for mindtechcare project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-^q3!by+2z9h5$o$8vd1j^x@em$1*-cte)inv_t)tk+9b4gea43"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "adminDev",
    "accounts",
    "rest_framework",
    "validations",
    "employees",
    "github",
    "trello",
    "dashboard",
    "plan",
    "rest_framework.authtoken",
]

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "settings")

# settings.py
import sys
import os

# Adiciona o diretório 'src' ao PYTHONPATH para que o Django encontre os apps
sys.path.insert(
    0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "src"))
)

# settings.py
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = (
    "smtp.gmail.com"  # exemplo de servidor de e-mail (ajuste conforme seu provedor)
)
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "itjobs.pim@gmail.com"  # seu e-mail
EMAIL_HOST_PASSWORD = "bdkgasbhgbxhxgex"  # sua senha de e-mail


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

CSRF_TRUSTED_ORIGINS = ["http://127.0.0.1:8000"]

ROOT_URLCONF = "mindtechcare.urls"

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
]


TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


WSGI_APPLICATION = "mindtechcare.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
    ],
}

JAZZMIN_UI_TWEAKS = {
    "theme": "lux",
    # "dark_mode_theme": "solar ",
}

JAZZMIN_SETTINGS = {
    # Título da janela (será o padrão de current_admin_site.site_title se estiver ausente ou None)
    "site_title": "Library Admin",
    # Título na tela de login (máximo 19 caracteres) (padrão: current_admin_site.site_header)
    "site_header": "Library",
    # Título da marca no canto superior esquerdo (máximo 19 caracteres) (padrão: current_admin_site.site_header)
    "site_brand": "MindTechCare",
    # Logo do site (deve estar nos arquivos estáticos), usado na marca no canto superior esquerdo
    "site_logo": "../static/images/favicon/logowhite.png",
    # Logo usada no formulário de login (padrão: site_logo)
    "login_logo": "../static/images/logo_mindtechcare.png",
    # Logo para formulário de login no tema escuro (padrão: login_logo)
    "login_logo_dark": None,
    # Classes CSS aplicadas à logo acima
    "site_logo_classes": "img-circle",
    # Caminho relativo para o favicon do site (padrão: site_logo) (idealmente 32x32 px)
    "site_icon": None,
    # Texto de boas-vindas na tela de login
    "welcome_sign": "Welcome to the library",
    # Texto de direitos autorais no rodapé
    "copyright": "Acme Library Ltd",
    # Lista de modelos para buscar na barra de pesquisa. Se omitido, a barra de busca é escondida.
    # Pode ser uma lista ou uma string simples (campo de pesquisa único)
    "search_model": ["auth.User", "auth.Group"],
    # Campo do modelo User que contém a imagem/avatar (ImageField/URLField/CharField ou função)
    "user_avatar": None,
    ############
    # Menu Topo #
    ############
    # Links colocados no menu superior
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {
            "name": "Support",
            "url": "https://github.com/farridav/django-jazzmin/issues",
            "new_window": True,
        },
        {"model": "auth.User"},
        {"app": "books"},
    ],
    #############
    # Menu Usuário #
    #############
    # Links adicionais no menu do usuário no canto superior direito (não permite tipo "app" na URL)
    "usermenu_links": [
        {
            "name": "Support",
            "url": "https://github.com/farridav/django-jazzmin/issues",
            "new_window": True,
        },
        {"model": "auth.user"},
    ],
    #############
    # Menu Lateral #
    #############
    # Exibir ou não o menu lateral
    "show_sidebar": True,
    # Expande o menu automaticamente
    "navigation_expanded": True,
    # Ocultar estes apps no menu lateral (ex: "auth")
    "hide_apps": [],
    # Ocultar estes modelos no menu lateral (ex: "auth.user")
    "hide_models": [],
    # Ordenar o menu lateral com base nessa lista (não precisa conter todos os apps/modelos)
    "order_with_respect_to": ["auth", "books", "books.author", "books.book"],
    # Links personalizados agrupados por app
    "custom_links": {
        "books": [
            {
                "name": "Make Messages",
                "url": "make_messages",
                "icon": "fas fa-comments",
                "permissions": ["books.view_book"],
            }
        ]
    },
    # Ícones personalizados para apps/modelos no menu lateral (ver link com lista de ícones FontAwesome)
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "authtoken.TokenProxy": "fa-solid fa-key",
        "github.AtividadeGitHub": "fa-brands fa-github",
        "github.RepositorioGitHub": "fa-brands fa-github",
        "trello.BoardTrello": "fa-brands fa-trello",
        "trello.CardTrello": "fa-brands fa-trello",
        "employees.Employee": "fas fa-users",
        "accounts.UserModel": "fas fa-user",
    },
    # Ícone padrão para apps (quando não especificado)
    "default_icon_parents": "fas fa-chevron-circle-right",
    # Ícone padrão para modelos (quando não especificado)
    "default_icon_children": "fas fa-circle",
    #################
    # Modal de Relacionamento #
    #################
    # Usar modais em vez de pop-ups
    "related_modal_active": False,
    #############
    # Ajustes de Interface #
    #############
    # Caminhos relativos para seus CSS/JS customizados (devem estar nos arquivos estáticos)
    "custom_css": "../static/css/custom_admin.css",
    "custom_js": None,
    # Usar fontes do Google Fonts CDN (ou use custom_css para fornecer sua fonte)
    "use_google_fonts_cdn": True,
    # Mostrar o personalizador de UI na barra lateral
    "show_ui_builder": False,
    ###############
    # Tela de Edição #
    ###############
    # Formato da tela de edição: opções possíveis:
    # - single (tudo em um formulário só)
    # - horizontal_tabs (padrão)
    # - vertical_tabs
    # - collapsible
    # - carousel
    "changeform_format": "horizontal_tabs",
    # Substituir formato da tela de edição por modelo específico
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
    },
    # Adicionar seletor de idioma no admin
    # "language_chooser": True,
}
