# Generated by Django 5.1.7 on 2025-03-30 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0003_alter_employee_accounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardTrello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_board', models.CharField(max_length=255)),
                ('trello_board_id', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AtividadeTrello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome_card', models.CharField(max_length=255)),
                ('data_atividade', models.DateTimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CardTrello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome_card', models.CharField(max_length=255)),
                ('data_criacao', models.DateTimeField()),
                ('trello_card_id', models.CharField(max_length=255, unique=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='trello.boardtrello')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards_trello', to='employees.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
