# Generated by Django 5.1.7 on 2025-04-04 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_accounts'),
        ('trello', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividadetrello',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='cardtrello',
            name='employee',
        ),
        migrations.AddField(
            model_name='atividadetrello',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='trello.boardtrello'),
        ),
        migrations.AddField(
            model_name='boardtrello',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boards_trello', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='cardtrello',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='trello.boardtrello'),
        ),
    ]
