# Generated by Django 5.1.7 on 2025-04-04 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0002_remove_atividadetrello_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardtrello',
            name='trello_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
