# Generated by Django 5.1.7 on 2025-04-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0004_cardtrello_employee_delete_atividadetrello'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardtrello',
            name='trello_token',
        ),
        migrations.AddField(
            model_name='boardtrello',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
