# Generated by Django 5.1.7 on 2025-05-01 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0005_remove_boardtrello_trello_token_boardtrello_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardtrello',
            name='trello_board_id',
            field=models.CharField(max_length=255),
        ),
    ]
