# Generated by Django 5.1.7 on 2025-03-27 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profissional',
            name='usuario',
        ),
    ]
