# Generated by Django 5.1.7 on 2025-03-27 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='senha',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
